name:  Java CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: Java CI

# on: 
#   push:
#     branches: master


# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v2
      
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
      
#       - name: Build with Maven
#         run: mvn -B package --file pom.xml
      
#       - name: Push to Docker Hub
#         uses: docker/build-push-action@v1
#         with:
#           username: ${{ secrets.belgiumbulldog }}
#           password: ${{ secrets.q6V3D2jegtgAMG7 }}
#           repository: belgiumbulldog/thirdpermanentevaluation
#           tag_with_ref: latest
